export default class {
    static timeout = {
        BUTTOM_SLIDER_FADE_TIMEOUT: "BUTTOM_SLIDER_FADE_TIMEOUT",
        RIGHT_SLIDER_FADE_TIMEOUT: "RIGHT_SLIDER_FADE_TIMEOUT"
    }
    static events = {
        EDIT_ELEMENT_WIDTH_CHANGE: "EDIT_ELEMENT_WIDTH_CHANGE",
        EDIT_ELEMENT_HEIGHT_CHANGE: "EDIT_ELEMENT_HEIGHT_CHANGE",
        PAGE_WIDTH_CHANGE: "PAGE_WIDTH_CHANGE",
        PAGE_HEIGHT_CHANGE: "PAGE_HEIGHT_CHANGE",
        EDITOR_SIZE_CHANGE: "EDITOR_SIZE_CHANGE"
    }
}