export class Constants {
    static events = {
        ELEMENTS_BUILD_FINISH: "ELEMENTS_BUILD_FINISH",
        ELEMENTS_ASSEMBLE_FINISH: "ELEMENTS_ASSEMBLE_FINISH",
        UI_INITIALIZED_OK: "UI_INITIALIZED_OK",
    }
}