export class Constants {

    static WIDTH_BASE_CHAR = 'i';
    static INDENTATION_WIDTH = 16;

    static timeout = {
        SET_CURSOUR_POSITION: "SET_CURSOUR_POSITION"
    }

    static events = {
        SELECTION_CHANGE: "SELECTION_CHANGE",
        TEXT_INPUT: "TEXT_INPUT",
        CONTAINER_SETED: "CONTAINER_SETED",
        ELEMENTS_CREATED: "ELEMENTS_CREATED",
        DOC_TREE_CREATED: "DOC_TREE_CREATED",
        DOC_TREE_ROOT_SETED: "DOC_TREE_ROOT_SETED",
    }

    static props = {
        DATA_UNIT_BLOCK_TYPE: "DATA_UNIT_BLOCK_TYPE",
        DATA_UNIT_BLOCK_VALUE: "DATA_UNIT_BLOCK_VALUE",

        PARAGRAPH_PLACEHOLDE: "PARAGRAPH_PLACEHOLDE",
        LINE_IS_PLACEHOLDER: "LINE_IS_PLACEHOLDER",
    }

}